services:
  sna-app:
    build: .
    container_name: streamlit_sna
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=admin123
    networks:
      - sna_network
    restart: always

  minio:
    image: minio/minio
    container_name: minio_storage
    ports:
      - "9000:9000" # API Port
      - "9001:9001" # Console Port (Dashboard)
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - sna_network
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx-streamlit
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - sna-app
    networks:
      - sna_network
    restart: always

networks:
  sna_network:
    driver: bridge

volumes:
  minio_data: