services:
  sna-app:
    build: .
    container_name: streamlit_sna
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx-streamlit
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - sna-app
    restart: always
